services:
  server:
    image: ubuntu:22.04
    container_name: "server"
    mem_limit: 2g
    privileged: true
    command: bash -c 'tail -f /dev/null'
    networks:
      main_network:
        ipv4_address: 192.168.1.198

networks:
  main_network:
    name: "main_network"
    ipam:
     config:
       - subnet: 192.168.1.128/25
         gateway: 192.168.1.197